// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

// import (
// 	"database/sql"
// 	"time"
// )

// type Account struct {
// 	ID           int64
// 	Name         string
// 	AccBalance   sql.NullFloat64
// 	AccNum       string
// 	CardNum      string
// 	Pin          string
// 	SecurityCode string
// 	CreditLimit  sql.NullFloat64
// 	MethodID     int32
// }
//
// type Balancesheet struct {
// 	ID         int64
// 	Month      int32
// 	Year       int32
// 	Allocation float64
// 	Paid       float64
// 	Remaining  float64
// 	CategoryID int32
// }
//
// type Category struct {
// 	ID   int64
// 	Name string
// }
//
// type Installment struct {
// 	ID            int64
// 	Name          string
// 	TotalCost     float64
// 	InterestRate  float64
// 	PeriodNum     int32
// 	PaidCost      float64
// 	CurrentPeriod int32
// 	PeriodCost    float64
// 	AccountID     int32
// }
//
// type Method struct {
// 	ID   int64
// 	Name sql.NullString
// }
//
// type Transaction struct {
// 	ID         int64
// 	Name       string
// 	Cost       float64
// 	Time       time.Time
// 	CategoryID int32
// }
